<?php
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
/**
* Implements hook_help().
*/
function configuration_form_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.configuration_form_example':
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('This is an example module.') . '</p>';
    return $output;
    default:
  }
}
/*
* implement hook_token_info()
*/
function configuration_form_example_token_info(){
  $types['custom_token_type'] = array(
    'name' => t('Custom token type'),
    'description' => t('Define custom token type')
  );	
  $tokens['custom_token_name'] = array(
    'name' => t('Custom token name'),
    'description' => t('Define custom token name')
  );
	
  return array(
    'types' => $types,
    'tokens' => array(
      'custom_token_type' => $tokens
    )
  );	
}

/*
* implement hook_token()
*/
function configuration_form_example_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata){
  $replacements = array();
  if($type == 'custom_token_type') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'custom_token_name':
        $text = 'Save Successfully!';
	      $replacements[$original] = $text;
	    break;
      }
    }
  }
  return $replacements;
}

/*
* implement hook_drupalhacks_latest_hack()
*/
// function configuration_form_example_drupalhacks_latest_hacks($list){
//   foreach($list as $key => $nid){
//     echo "<pre>"; print_r($nid);
//   }
// }
