name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core_version_requirement: ^9.4 || ^10
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2023-02-18
version: '4.0.0'
project: 'examples'
datestamp: 1676730027
